Repository GSG-G8/LMAR_Express, pull requests merged in 2020-01, with the labels that each got.

#3 craete initial files
  cart.html
  css/style.css
  customer.html
  fonts/.gitkeep
  images/.gitkeep
  script/dom.js
  script/logic.js
  seller.html
Labels: awaiting review

#9 2 create layout customer
  customer.html
  images/2591879936_67270a1b-efca-4ecf-8988-186863f6853d.png
  images/freestocks-org-_3Q3tsJ01nc-unsplash.jpg
Labels: awaiting review

#10 Create layout for seller
  seller.html
Labels: awaiting review

#17 8 styling customer page
  css/style.css
  customer.html
  fonts/Roboto-Bold.ttf
  fonts/Roboto-Medium.ttf
  fonts/Roboto-Regular.ttf
Labels: in progress

#20 Add edit form to the seller* page
  seller.html
Labels: awaiting review

#21 18 complete customer stling
  css/style.css
  customer.html
  images/27001163_MediumBlueDenim_001_ProductLarge.jpg
  images/28092304_modern-business-woman-portrait.jpg
  images/search-icon.png
Labels: awaiting review

#22 12 dom seller
  script/dom.js
  seller.html
Labels: JS, awaiting review

#23 Styling the Seller Page
  css/style.css
  customer.html
Labels: CSS, Front-End

#26 delete and search function with their test
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/logic.js.html
  coverage/lcov.info
  script/logic.js
  test.js
Labels: JS, awaiting review

#27 11 don customer
  Customer.html
  script/dom.js
  script/logic.js
  seller.html
Labels: JS, awaiting review

#29 25 responsive design
  Customer.html
  css/style.css
  seller.html
Labels: awaiting review

#30 create cart page
  cart.html
  css/style.css
Labels: CSS, Front-End, awaiting review

#32 update readme file
  README.md
Labels: awaiting review, documentation

#33 Dom
  script/dom.js
  script/logic.js
  seller.html
Labels: JS

#61 Fix issues
  cart.html
  index.html
  script/dom.js
  script/logic.js
  seller.html
Labels: awaiting review
